### PR TITLE
Improve docs

### PR DESCRIPTION
**Pull request by jugglinmike**
@caitp @rwaldron Mind giving this a once-over for me?

Resolves

- https://github.com/jshint/jshint/issues/1902
- https://github.com/jshint/jshint/issues/1745

### CODE REVIEW

**Comment by caitp** [comment]
are the api docs automatically generated from the jshint repository? If not, we should really fix that, or they'll go out of sync very easily.

**Comment by jugglinmike** [comment]
They are not. I agree that generating them would be preferable, and that's what has kept me from writing this documentation for so long. I ultimately decided it was more important to publish *something*, even if it wasn't perfect. I haven't been able to find the time to set up documentation generation for the API, but in the mean time users are on their own when it comes to using it. There have been no changes to the API for as long as I've been on the project, so I think this is acceptable (for now at least).

**Comment by caitp** [comment]
I'm fine with landing this, but we should really use jsdoc or dgeni in core asap

**Comment by jugglinmike** [comment]
Thank you

**Comment by macgyver** [comment]
Just curious - where can I find this documentation? It doesn't seem to be on http://jshint.com/docs/options/

**Comment by jugglinmike** [comment]
That page's documentation is derived from the JSHint source code:

> This page's content is sourced from the JSHint project repository. If you spot an error, please open an issue or (better yet) make a pull request!

The changes introduced by this pull request are dispersed across [the other documentation pages](http://jshint.com/docs/). You can use the filename as a general guide, but the specific URLs are specified via JSON values declared at the beginning of each file.

**Comment by macgyver** [comment]
Got it, thanks!

**Pull request merged**
